#ifndef ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_VRBRAIN_H_INCLUDED
#define ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_VRBRAIN_H_INCLUDED


#define HAL_BOARD_SUBTYPE_VRBRAIN_V45      4000
#define HAL_BOARD_SUBTYPE_VRBRAIN_V51      4001
#define HAL_BOARD_SUBTYPE_VRBRAIN_V52      4002
#define HAL_BOARD_SUBTYPE_VRUBRAIN_V51     4003
#define HAL_BOARD_SUBTYPE_VRUBRAIN_V52     4004
#define HAL_BOARD_SUBTYPE_VRCORE_V10       4005
#define HAL_BOARD_SUBTYPE_VRBRAIN_V54      4006

#endif // ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_VRBRAIN_H_INCLUDED
