#ifndef ARDUPILOT_AP_COMPASS_DEVICE_IDS_H_INCLUDED
#define ARDUPILOT_AP_COMPASS_DEVICE_IDS_H_INCLUDED

// compass product id
//#define AP_COMPASS_TYPE_UNKNOWN         0x00
//#define AP_COMPASS_TYPE_HIL             0x01
#define AP_COMPASS_TYPE_HMC5843         0x02
#define AP_COMPASS_TYPE_HMC5883L        0x03
//#define AP_COMPASS_TYPE_PX4             0x04
//#define AP_COMPASS_TYPE_VRBRAIN         0x05
#define AP_COMPASS_TYPE_AK8963_MPU9250  0x06
#define AP_COMPASS_TYPE_AK8963_I2C      0x07
#define AP_COMPASS_TYPE_LSM303D         0x08
#define AP_COMPASS_TYPE_LSM9DS1         0x09
#define AP_COMPASS_TYPE_BMM150          0x0A

#endif // ARDUPILOT_AP_COMPASS_DEVICE_IDS_H_INCLUDED
