#ifndef ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_BAROMETER_H_INCLUDED
#define ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_BAROMETER_H_INCLUDED

#define HAL_BARO_BMP085      1
#define HAL_BARO_MS5611_I2C  2
#define HAL_BARO_MS5611_SPI  3
#define HAL_BARO_MS5607_I2C  4
#define HAL_BARO_PX4         5
#define HAL_BARO_HIL         6
#define HAL_BARO_VRBRAIN     7
#define HAL_BARO_MS5637_I2C  8
#define HAL_BARO_QFLIGHT     9
#define HAL_BARO_QURT       10

#endif // ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_BAROMETER_H_INCLUDED
