#ifndef ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_INERTIALSENSOR_H_INCLUDED
#define ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_INERTIALSENSOR_H_INCLUDED

#define HAL_INS_MPU60XX_SPI  2
#define HAL_INS_MPU60XX_I2C  3
#define HAL_INS_HIL          4
#define HAL_INS_PX4          5
#define HAL_INS_L3G4200D     7
#define HAL_INS_VRBRAIN      8
#define HAL_INS_MPU9250_SPI  9
#define HAL_INS_L3GD20      10
#define HAL_INS_LSM9DS0     11
#define HAL_INS_RASPILOT    12
#define HAL_INS_MPU9250_I2C 13
#define HAL_INS_BH          14
#define HAL_INS_QFLIGHT     15
#define HAL_INS_QURT        16
#define HAL_INS_BBBMINI     17
#define HAL_INS_AERO        18

#endif // ARDUPILOT_LIBRARIES_AP_HAL_BOARDS_INERTIALSENSOR_H_INCLUDED
